### ISSUE TITLE
Option to change highlighting for gitDiff

### ISSUE THREAD

**Issue by EncodePanda** [chrissound/GitChapter#1]
For gitDiff it makes more sense to show `diff` color highlighting on the output (red for removed, green for added lines), rather than highlighting of the given language.

I'm happy to create PR for this. Can you show me part of the code that renders the output of gitDiff?

**Comment by chrissound** [comment]
Thanks for your interest!

Hmmm so the suggested behavior makes sense, though I think it comes down to the formatting of the markdown/chapter.

For example, in https://github.com/chrissound/NextUpHarticle/blame/master/sections/2_Input%20output.md#L6

Which is live here: "Section 2 - Input output" https://trycatchchris.co.uk/post/view/Lets-build-a-command-line-To-do-application-using-Haskell


I'm doing:

    ```haskell
    {{ gitDiff src/Main.hs }}
    ```

When I guess I should be doing a diff(?) syntax instead? But this comes down to the "gitchapter enabled project" itself (the templates?) rather than the project itself.

---

However, I think it would make sense to handle the diff formatting with gitchapter rather than relying on a user to create the appropriate formatting. In other words, to output something like:

    ```diff
    renderedGitDiffBlaBla
    ```

Instead of just the

    renderedGitDiffBlaBla

So feel free to make a PR for this :) I'm assuming the `diff` highlighting is an actual markdown/pandoc option. This does mean it'll be a breaking change but it's fine (I don't know anyone using this yet!). It also means it might be hardcoded to markdown format for now - but that's fine, we can add another `gitDiffRaw` as an alternative in future.

Sorry quite a lengthy response! Hopefully it makes sense!


The relevant code:

https://github.com/chrissound/GitChapter/blob/56dea57a853037e7167397017c1b1e76b3ea970e/src/Render.hs#L86

https://github.com/chrissound/GitChapter/blob/881dda7566693ef84d9d39f6569c1e997cc0fe01/src/Operations.hs#L65

**Comment by EncodePanda** [comment]
You are right, I was mistaken by thinking the highlight method is predefined in the tool. Here the user has freedom. I think this approach (the current one) is better (sometimes I want to render with `diff` highlighting, sometimes with `Haskell` (depending on what I want to emphasize). Thus I'm closing this ticket for now. Thank you for feedback.

By the way, I'm starting today writing my first blog post with your tool. Let's see how it goes :)
